### ISSUE TITLE
Guide for new contributor :)

### ISSUE THREAD

**Issue by oltarzewskik** [wisepythagoras/dimoschain#2]
Hello, I am Karol I find this project really interesting and would love to contribute to it

It would be nice if there was list of issues on github and some kind of chat for discussing topics not suitable for github issues.

I succesfully tested dimoschain on my local container, but it was little bit tricky.

What do you think about moving to go modules? I can try to make a PR with guide to installation for development in the new way

**Comment by wisepythagoras** [comment]
Hi @oltarzewskik!

Thank you for your interest in the project. That's very reassuring. There is no chat for now, since I was the only one working on the project.

The reason I didn't go with go modules was because the underlying library that I use for crypto (https://github.com/decred/dcrd/dcrec/secp256k1) [seemed unmaintained on pkg.go.dev](https://pkg.go.dev/github.com/decred/dcrd/dcrec/secp256k1?tab=versions). It says that the latest version is v2.0.0 from Oct 7, 2019, and I wanted to keep the up to date version from the repository.

At some point, however, it would be great to move to go modules, so if you'd like to make that PR, it would be welcomed, but I'd like to emphasize that I want the latest possible versions, especially when talking about crypto. I started writing tests in Go though, so that's something to take into consideration. You can run them with [this script](https://github.com/wisepythagoras/dimoschain/blob/master/tools/gen_coverage.sh).

If you are interested in contributing, I should work faster on the whitepaper and try to make a TODO list. But for argument's sake this is what I was planning on working on next:

* Implement the three defined commands and their actions.
  - Exit just exits
  - Accept a transaction to send, but just keep it in a mempool (Redis?) for now
  - Send the latest blocks with the update command
* Implement the above commands on the background service (which is the client) as well.
* Implement horizontal segmentation on the database.

Thank you again!

**Comment by oltarzewskik** [comment]
Hi @wisepythagoras 

I am starting to work on moving to go modules since I am not yet familiar with code and how project exactly works.
If you will have some prototype of whitepaper it would help me a lot in understanding the project

This is my email: 2004karol@gmail.com you can send it there if you want, I will highly appreciete that

**Comment by wisepythagoras** [comment]
It's gone through many revisions and the current one is just in notes, so it would take me some time to write it up, even as a draft. In the coming days I can start on that, though. This is the reason why I was focusing more on the common functionality between cryptocurrencies. Ex. peer sends a transaction to node, node verifies the transaction, etc.
